renamedirs = [ "[repo]/src/factory",]
editlines = [ 
[ "[repo]/Makefile", "APPNAME=\"factory\"", "APPNAME=\"[newname]\"",],
[ "[repo]/pyproject.toml", "name = \"factory\"", "name = \"[newname]\"",],
[ "[repo]/pyproject.toml", "packages = [{include = \"factory\", from = \"src\"}]", "packages = [{include = \"[newname]\", from = \"src\"}]",],
]
inherited = [
"Makefile",
"LICENSE",
"MANIFEST.in",
".gitignore",
"src/factory/utils.py",
"src/factory/settings.py",
]
