renamedirs = [ "[repo]/src/standardnib",]
editlines = [ 
[ "[repo]/Makefile", "APPNAME=\"standardnib\"", "APPNAME=\"[newname]\"",],
[ "[repo]/pyproject.toml", "name = \"standardnib\"", "name = \"[newname]\"",],
[ "[repo]/pyproject.toml", "packages = [{include = \"standardnib\", from = \"src\"}]", "packages = [{include = \"[newname]\", from = \"src\"}]",],
[ "[repo]/pyproject.toml", "standardnib = 'standardnib.cli:cli'", "\"[newname]\" = '\"[newname]\".cli:cli'",],
]
inherited = [
"Makefile",
"LICENSE",
"MANIFEST.in",
".gitignore",
]
