[project]
name = "extcython"
version = "0.1.0"
description = "Add your description here"
dependencies = []
requires-python = "== 3.11.8"

[build-system]
requires = ["setuptools", "cython"]
build-backend = "setuptools.build_meta"



