name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Run bash-environment-manager      
      run: |
        mkdir -p .repo
        curl https://raw.githubusercontent.com/terminal-labs-bem/shelf/main/prepfiles/mock_vagrant.sh --output .repo/mock_vagrant.sh
        cd /vagrant; sudo su vagrant -c "sudo make rye"
