name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Run bash-environment-manager      
      run: |
        cd /vagrant; sudo su vagrant -c "sudo make rye"
